/aruco_node:
  ros__parameters:
    poll_delay_seconds: 0.2
    marker_size: 0.050
    aruco_dictionary_id: "DICT_5X5_250"
    camera_index: 2
    calibration_resolution: [1920, 1080]
    capture_resolution: [1920, 1080]
    # camera_destination_index: 10
    # Data comes from a C920 in the lab calibrated with an 8x6 grid.
    camera_matrix: [1727.79073,    0.     , 1063.47911,
                    0.     , 1768.42988,  733.47827,
                    0.     ,    0.     ,    1.     ]
    distortion_coefficients: [0.383893, -0.475512, 0.031456, 0.005959, 0.000000]

# This was the complete set of calibration data:
# image_width: 1920
# image_height: 1080
# camera_name: narrow_stereo
# camera_matrix:
#   rows: 3
#   cols: 3
#   data: [1727.79073,    0.     , 1063.47911,
#             0.     , 1768.42988,  733.47827,
#             0.     ,    0.     ,    1.     ]
# distortion_model: plumb_bob
# distortion_coefficients:
#   rows: 1
#   cols: 5
#   data: [0.383893, -0.475512, 0.031456, 0.005959, 0.000000]
# rectification_matrix:
#   rows: 3
#   cols: 3
#   data: [1., 0., 0.,
#          0., 1., 0.,
#          0., 0., 1.]
# projection_matrix:
#   rows: 3
#   cols: 4
#   data: [1865.86427,    0.     , 1066.75093,    0.     ,
#             0.     , 1879.6054 ,  758.5378 ,    0.     ,
#             0.     ,    0.     ,    1.     ,    0.     ]